### ISSUE TITLE
Integrate bulk processing tool

### ISSUE THREAD

**Issue by dracos** [mysociety/mapit.mysociety.org#38]
Transferred from https://github.com/mysociety/mapit-bulk-processing/issues/1

- [x] Design lookover of process
    - [x] Form fields (column select, skip bad rows tickbox, pick which area types list, email/description)
    - [x] Error messages
    - [x] Table display
    - [x] You'll get an email/download your CSV pages
- Advertising this elsewhere on site => #46
- [x] Copy for each step of process, success email

**Comment by dracos** [comment]
Just to note this is live at https://mapit.mysociety.org/bulk/ - I reused the front end code from accounts, so that looks okay, but the things above are the outstanding things potentially left.

**Comment by MyfanwyNixon** [comment]
Here's a draft for some copy and the success email, plus error messages. 
https://docs.google.com/document/d/1wo2pTTV26gdIz85rUgE4ODTV5IdUtuc4Yp-XsceCd9o/edit#

I've probably made some wrong assumptions so feel free to change it!

**Comment by zarino** [comment]
Notes on the visual elements:

- The file input with the text input styling (because we’re re-using the `.account-form__field` styles) looks a bit funky, but I guess it's still usable. I can spend a little time fixing this if you want. => #47
- [x] "Next" buttons should have `btn--primary` not `btn-primary` class. (Sorry, this isn’t a Bootstrap site, despite the classes looking kinda similar.)
- [x] I wonder whether it'd make more sense to swap the vertical order of the "Now tell us where the postcodes are" and "This is what your file looks like" sections? So, first you show them what their file looks like, and *then* you ask them to make a selection from the dropdown and click "Next".
- [x] I’d probably put the "Prev" and "Next" buttons on the same line, in that order (rather than wrapping the "Prev" in a `<p>` after the "Next" button).
- [x] Also, any chance we could make the `personal_details-email` input a `<input type="email">` rather than `<input type="text">`?

**Comment by MyfanwyNixon** [comment]
> I wonder whether it'd make more sense to swap the vertical order of the "Now tell us where the postcodes are" and "This is what your file looks like" sections

I vote for this (though you'd need to only show a few lines I think - the depth it is at the moment, you'd run the risk of the text underneath being overlooked).

**Comment by dracos** [comment]
Most/all the above integrated, and live, moved bits to new tickets, considering this closed.
